services:
  app:
    container_name: alpaca-webui
    image: forloopse/alpaca-webui:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app
      - /app/node_modules
      - /app/.next
      - db:/app/db
    restart: unless-stopped
    networks:
      - net
    ports:
      - '3033:3000'
    environment:
      CRYPTO_SECRET_KEY: 'CHANGE!'

  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    ports:
      - 8083:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    networks:
      - net
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

volumes:
  weaviate_data:
    name: alpacawebui_weaviate_data
  db:
    name: alpacawebui_db
    driver: local

networks:
  net:
    driver: bridge
